// NOTE: This script generated by editor automatically. No need to edit manually!
// ReSharper disable RedundantUsingDirective

using System.Collections.Generic;
using UniSharper.Data.Metadata;
using UniSharper.Extensions;
using UnityEngine;
using UnityEngine.Scripting;
using ColorUtility = UniSharper.Extensions.ColorUtility;

// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable UnusedMember.Global

namespace UniSharper.Data.Metadata.Samples
{
	/// <summary>
	/// PlayerMetadata
	/// Note: Generated by Editor automatically. Please don't edit this file manually!
	/// </summary>
	public partial class PlayerMetadata : MetadataEntity
	{

		/// <summary>
		/// Initializes a new instance of the <see cref="PlayerMetadata"/> class.
		/// </summary>
		[Preserve]
		public PlayerMetadata()
		{
		}

		/// <summary>
		/// ID
		/// </summary>
		public long Id { get; set; }

		/// <summary>
		/// Badge
		/// </summary>
		public long Badge { get; set; }

		/// <summary>
		/// Avatar
		/// </summary>
		public long Avatar { get; set; }

		/// <summary>
		/// Name
		/// </summary>
		public string Name { get; set; }
	}
}
