// NOTE: This script generated by editor automatically. No need to edit manually!
// ReSharper disable RedundantUsingDirective

using System.Collections.Generic;
using UnityEngine.Scripting;
using UniSharper.Data.Metadata;
using UnityEngine;

// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable UnusedMember.Global

namespace UniSharper.Data.Metadata.Samples
{
	/// <summary>
	/// UnityTypeSampleMetadata
	/// Note: Generated by Editor automatically. Please don't edit this file manually!
	/// </summary>
	public partial class UnityTypeSampleMetadata : MetadataEntity
	{
		private Vector2[] vector2ArraySample;

		private Vector2Int[] vector2IntArraySample;

		private Vector3[] vector3ArraySample;

		private Vector3Int[] vector3IntArraySample;

		private Vector4[] vector4ArraySample;

		private RangeInt[] rangeIntArraySample;

		private Quaternion[] quaternionArraySample;

		private Rect[] rectArraySample;

		private RectInt[] rectIntArraySample;

		private Color[] colorArraySample;

		private Color32[] color32ArraySample;


		/// <summary>
		/// Initializes a new instance of the <see cref="UnityTypeSampleMetadata"/> class.
		/// </summary>
		[Preserve]
		public UnityTypeSampleMetadata()
		{
		}

		/// <summary>
		/// ID
		/// </summary>
		public long ID { get; set; }

		/// <summary>
		/// Vector2 Value
		/// </summary>
		public float[] Vector2SampleValue { get; set; }

		/// <summary>
		/// Vector2 Value
		/// </summary>
		public Vector2 Vector2Sample => new(Vector2SampleValue[0], Vector2SampleValue[1]);

		/// <summary>
		/// Vector2Int Value
		/// </summary>
		public int[] Vector2IntSampleValue { get; set; }

		/// <summary>
		/// Vector2Int Value
		/// </summary>
		public Vector2Int Vector2IntSample => new(Vector2IntSampleValue[0], Vector2IntSampleValue[1]);

		/// <summary>
		/// Vector3 Value
		/// </summary>
		public float[] Vector3SampleValue { get; set; }

		/// <summary>
		/// Vector3 Value
		/// </summary>
		public Vector3 Vector3Sample => new(Vector3SampleValue[0], Vector3SampleValue[1], Vector3SampleValue[2]);

		/// <summary>
		/// Vector3Int Value
		/// </summary>
		public int[] Vector3IntSampleValue { get; set; }

		/// <summary>
		/// Vector3Int Value
		/// </summary>
		public Vector3Int Vector3IntSample => new(Vector3IntSampleValue[0], Vector3IntSampleValue[1], Vector3IntSampleValue[2]);

		/// <summary>
		/// Vector4 Value
		/// </summary>
		public float[] Vector4SampleValue { get; set; }

		/// <summary>
		/// Vector4 Value
		/// </summary>
		public Vector4 Vector4Sample => new(Vector4SampleValue[0], Vector4SampleValue[1], Vector4SampleValue[2], Vector4SampleValue[3]);

		/// <summary>
		/// RangeInt Value
		/// </summary>
		public int[] RangeIntSampleValue { get; set; }

		/// <summary>
		/// RangeInt Value
		/// </summary>
		public RangeInt RangeIntSample => new(RangeIntSampleValue[0], RangeIntSampleValue[1]);

		/// <summary>
		/// Quaternion Value
		/// </summary>
		public float[] QuaternionSampleValue { get; set; }

		/// <summary>
		/// Quaternion Value
		/// </summary>
		public Quaternion QuaternionSample => new(QuaternionSampleValue[0], QuaternionSampleValue[1], QuaternionSampleValue[2], QuaternionSampleValue[3]);

		/// <summary>
		/// Rect Value
		/// </summary>
		public float[] RectSampleValue { get; set; }

		/// <summary>
		/// Rect Value
		/// </summary>
		public Rect RectSample => new(RectSampleValue[0], RectSampleValue[1], RectSampleValue[2], RectSampleValue[3]);

		/// <summary>
		/// RectInt Value
		/// </summary>
		public int[] RectIntSampleValue { get; set; }

		/// <summary>
		/// RectInt Value
		/// </summary>
		public RectInt RectIntSample => new(RectIntSampleValue[0], RectIntSampleValue[1], RectIntSampleValue[2], RectIntSampleValue[3]);

		/// <summary>
		/// Color Value
		/// </summary>
		public float[] ColorSampleValue { get; set; }

		/// <summary>
		/// Color Value
		/// </summary>
		public Color ColorSample => new(ColorSampleValue[0], ColorSampleValue[1], ColorSampleValue[2], ColorSampleValue[3]);

		/// <summary>
		/// Color32 Value
		/// </summary>
		public byte[] Color32SampleValue { get; set; }

		/// <summary>
		/// Color32 Value
		/// </summary>
		public Color32 Color32Sample => new(Color32SampleValue[0], Color32SampleValue[1], Color32SampleValue[2], Color32SampleValue[3]);

		/// <summary>
		/// Vector2 Array Value
		/// </summary>
		public float[] Vector2ArraySampleValue { get; set; }

		/// <summary>
		/// Vector2 Array Value
		/// </summary>
		public Vector2[] Vector2ArraySample
		{
			get
			{
				if (vector2ArraySample != null)
					return vector2ArraySample;

				var list = new List<Vector2>();
				for (var i = 0; i < Vector2ArraySampleValue.Length; i += 2)
				{
					var parameter1 = Vector2ArraySampleValue[i];
					var parameter2 = Vector2ArraySampleValue[i + 1];
					list.Add(new Vector2(parameter1, parameter2));
				}
				vector2ArraySample = list.ToArray();
				return vector2ArraySample;
			}
		}

		/// <summary>
		/// Vector2Int Array Value
		/// </summary>
		public int[] Vector2IntArraySampleValue { get; set; }

		/// <summary>
		/// Vector2Int Array Value
		/// </summary>
		public Vector2Int[] Vector2IntArraySample
		{
			get
			{
				if (vector2IntArraySample != null)
					return vector2IntArraySample;

				var list = new List<Vector2Int>();
				for (var i = 0; i < Vector2IntArraySampleValue.Length; i += 2)
				{
					var parameter1 = Vector2IntArraySampleValue[i];
					var parameter2 = Vector2IntArraySampleValue[i + 1];
					list.Add(new Vector2Int(parameter1, parameter2));
				}
				vector2IntArraySample = list.ToArray();
				return vector2IntArraySample;
			}
		}

		/// <summary>
		/// Vector3 Array Value
		/// </summary>
		public float[] Vector3ArraySampleValue { get; set; }

		/// <summary>
		/// Vector3 Array Value
		/// </summary>
		public Vector3[] Vector3ArraySample
		{
			get
			{
				if (vector3ArraySample != null)
					return vector3ArraySample;

				var list = new List<Vector3>();
				for (var i = 0; i < Vector3ArraySampleValue.Length; i += 3)
				{
					var parameter1 = Vector3ArraySampleValue[i];
					var parameter2 = Vector3ArraySampleValue[i + 1];
					var parameter3 = Vector3ArraySampleValue[i + 2];
					list.Add(new Vector3(parameter1, parameter2, parameter3));
				}
				vector3ArraySample = list.ToArray();
				return vector3ArraySample;
			}
		}

		/// <summary>
		/// Vector3Int Array Value
		/// </summary>
		public int[] Vector3IntArraySampleValue { get; set; }

		/// <summary>
		/// Vector3Int Array Value
		/// </summary>
		public Vector3Int[] Vector3IntArraySample
		{
			get
			{
				if (vector3IntArraySample != null)
					return vector3IntArraySample;

				var list = new List<Vector3Int>();
				for (var i = 0; i < Vector3IntArraySampleValue.Length; i += 3)
				{
					var parameter1 = Vector3IntArraySampleValue[i];
					var parameter2 = Vector3IntArraySampleValue[i + 1];
					var parameter3 = Vector3IntArraySampleValue[i + 2];
					list.Add(new Vector3Int(parameter1, parameter2, parameter3));
				}
				vector3IntArraySample = list.ToArray();
				return vector3IntArraySample;
			}
		}

		/// <summary>
		/// Vector4 Array Value
		/// </summary>
		public float[] Vector4ArraySampleValue { get; set; }

		/// <summary>
		/// Vector4 Array Value
		/// </summary>
		public Vector4[] Vector4ArraySample
		{
			get
			{
				if (vector4ArraySample != null)
					return vector4ArraySample;

				var list = new List<Vector4>();
				for (var i = 0; i < Vector4ArraySampleValue.Length; i += 4)
				{
					var parameter1 = Vector4ArraySampleValue[i];
					var parameter2 = Vector4ArraySampleValue[i + 1];
					var parameter3 = Vector4ArraySampleValue[i + 2];
					var parameter4 = Vector4ArraySampleValue[i + 3];
					list.Add(new Vector4(parameter1, parameter2, parameter3, parameter4));
				}
				vector4ArraySample = list.ToArray();
				return vector4ArraySample;
			}
		}

		/// <summary>
		/// RangeInt Array Value
		/// </summary>
		public int[] RangeIntArraySampleValue { get; set; }

		/// <summary>
		/// RangeInt Array Value
		/// </summary>
		public RangeInt[] RangeIntArraySample
		{
			get
			{
				if (rangeIntArraySample != null)
					return rangeIntArraySample;

				var list = new List<RangeInt>();
				for (var i = 0; i < RangeIntArraySampleValue.Length; i += 2)
				{
					var parameter1 = RangeIntArraySampleValue[i];
					var parameter2 = RangeIntArraySampleValue[i + 1];
					list.Add(new RangeInt(parameter1, parameter2));
				}
				rangeIntArraySample = list.ToArray();
				return rangeIntArraySample;
			}
		}

		/// <summary>
		/// Quaternion Array Value
		/// </summary>
		public float[] QuaternionArraySampleValue { get; set; }

		/// <summary>
		/// Quaternion Array Value
		/// </summary>
		public Quaternion[] QuaternionArraySample
		{
			get
			{
				if (quaternionArraySample != null)
					return quaternionArraySample;

				var list = new List<Quaternion>();
				for (var i = 0; i < QuaternionArraySampleValue.Length; i += 4)
				{
					var parameter1 = QuaternionArraySampleValue[i];
					var parameter2 = QuaternionArraySampleValue[i + 1];
					var parameter3 = QuaternionArraySampleValue[i + 2];
					var parameter4 = QuaternionArraySampleValue[i + 3];
					list.Add(new Quaternion(parameter1, parameter2, parameter3, parameter4));
				}
				quaternionArraySample = list.ToArray();
				return quaternionArraySample;
			}
		}

		/// <summary>
		/// Rect Array Value
		/// </summary>
		public float[] RectArraySampleValue { get; set; }

		/// <summary>
		/// Rect Array Value
		/// </summary>
		public Rect[] RectArraySample
		{
			get
			{
				if (rectArraySample != null)
					return rectArraySample;

				var list = new List<Rect>();
				for (var i = 0; i < RectArraySampleValue.Length; i += 4)
				{
					var parameter1 = RectArraySampleValue[i];
					var parameter2 = RectArraySampleValue[i + 1];
					var parameter3 = RectArraySampleValue[i + 2];
					var parameter4 = RectArraySampleValue[i + 3];
					list.Add(new Rect(parameter1, parameter2, parameter3, parameter4));
				}
				rectArraySample = list.ToArray();
				return rectArraySample;
			}
		}

		/// <summary>
		/// RectInt Array Value
		/// </summary>
		public int[] RectIntArraySampleValue { get; set; }

		/// <summary>
		/// RectInt Array Value
		/// </summary>
		public RectInt[] RectIntArraySample
		{
			get
			{
				if (rectIntArraySample != null)
					return rectIntArraySample;

				var list = new List<RectInt>();
				for (var i = 0; i < RectIntArraySampleValue.Length; i += 4)
				{
					var parameter1 = RectIntArraySampleValue[i];
					var parameter2 = RectIntArraySampleValue[i + 1];
					var parameter3 = RectIntArraySampleValue[i + 2];
					var parameter4 = RectIntArraySampleValue[i + 3];
					list.Add(new RectInt(parameter1, parameter2, parameter3, parameter4));
				}
				rectIntArraySample = list.ToArray();
				return rectIntArraySample;
			}
		}

		/// <summary>
		/// Color Array Value
		/// </summary>
		public float[] ColorArraySampleValue { get; set; }

		/// <summary>
		/// Color Array Value
		/// </summary>
		public Color[] ColorArraySample
		{
			get
			{
				if (colorArraySample != null)
					return colorArraySample;

				var list = new List<Color>();
				for (var i = 0; i < ColorArraySampleValue.Length; i += 4)
				{
					var parameter1 = ColorArraySampleValue[i];
					var parameter2 = ColorArraySampleValue[i + 1];
					var parameter3 = ColorArraySampleValue[i + 2];
					var parameter4 = ColorArraySampleValue[i + 3];
					list.Add(new Color(parameter1, parameter2, parameter3, parameter4));
				}
				colorArraySample = list.ToArray();
				return colorArraySample;
			}
		}

		/// <summary>
		/// Color32 Array Value
		/// </summary>
		public byte[] Color32ArraySampleValue { get; set; }

		/// <summary>
		/// Color32 Array Value
		/// </summary>
		public Color32[] Color32ArraySample
		{
			get
			{
				if (color32ArraySample != null)
					return color32ArraySample;

				var list = new List<Color32>();
				for (var i = 0; i < Color32ArraySampleValue.Length; i += 4)
				{
					var parameter1 = Color32ArraySampleValue[i];
					var parameter2 = Color32ArraySampleValue[i + 1];
					var parameter3 = Color32ArraySampleValue[i + 2];
					var parameter4 = Color32ArraySampleValue[i + 3];
					list.Add(new Color32(parameter1, parameter2, parameter3, parameter4));
				}
				color32ArraySample = list.ToArray();
				return color32ArraySample;
			}
		}
	}
}
